// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeEmprestimo.Data;

#nullable disable

namespace SistemaDeEmprestimo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207010635_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeEmprestimo.Models.Emprestimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLimite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserCredorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserDevedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserCredorId");

                    b.HasIndex("UserDevedorId");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("SistemaDeEmprestimo.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SistemaDeEmprestimo.Models.Emprestimo", b =>
                {
                    b.HasOne("SistemaDeEmprestimo.Models.User", "UserCredor")
                        .WithMany("EmprestimoComoCredor")
                        .HasForeignKey("UserCredorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeEmprestimo.Models.User", "UserDevedor")
                        .WithMany("EmprestimoComoDevedor")
                        .HasForeignKey("UserDevedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserCredor");

                    b.Navigation("UserDevedor");
                });

            modelBuilder.Entity("SistemaDeEmprestimo.Models.User", b =>
                {
                    b.Navigation("EmprestimoComoCredor");

                    b.Navigation("EmprestimoComoDevedor");
                });
#pragma warning restore 612, 618
        }
    }
}
